# Generated by Django 4.2.23 on 2025-09-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='sin_imagen/', upload_to='inmuebles/'),
        ),
        migrations.AddField(
            model_name='perfiluser',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='inmuebles/'),
        ),
    ]
