# Generated by Django 4.2.23 on 2025-09-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_inmueble_imagen_perfiluser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='no_img.jpg', upload_to='inmuebles/'),
        ),
    ]
